# This workflow will build a Java project with Gradle
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

on:
  push:
  pull_request:
    branches: [ master ]

defaults:
  run:
    shell: bash

jobs:
  build:
    environment: CIRelease
    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-latest', 'windows-latest' ]
    runs-on: ${{ matrix.os }}
    permissions:
      checks: write
      pull-requests: write
    name: Build & Test with Java ${{ matrix.Java }} (${{ matrix.os }})
    steps:
      - name: Setup
        uses: IntershopCommunicationsAG/.github/actions/gradle-plugin-setup@v3
      - name: Build
        uses: IntershopCommunicationsAG/.github/actions/gradle-plugin-build@v3
