# This workflow will build a Java project with Gradle
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

on:
  push:
    tags:
      - '*'

jobs:
  release:
    environment: CIRelease
    runs-on: ubuntu-latest
    name: Run release build from tag
    steps:
      - name: Setup
        uses: IntershopCommunicationsAG/.github/actions/gradle-plugin-setup@v2
      - name: Release
        uses: IntershopCommunicationsAG/.github/actions/gradle-plugin-release@v2
        with:
          signing-file: ${{ secrets.SIGNINGFILE }}
          signing-key-id: ${{ secrets.SIGNINGKEYID }}
          signing-password: ${{ secrets.SIGNINGPASSWORD }}
          api-key: ${{ secrets.APIKEY }}
          api-secret: ${{ secrets.APISECRET }}
          sonatype-user: ${{ secrets.SONATYPEUSER }}
          sonatype-password: ${{ secrets.SONATYPEPASSWORD }}
